config/routes.rb
Rails.application.routes.draw do
  get 'paginas/index'

  get 'paginas/localizacao'

  resources :funcionarios

  root 'paginas#index'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:matricula, :nome, :endereco, :telefone, :salario, :sexo, :dtadmissao)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def index
  end

  def localizacao
  	@empresa = "Instituto Federal Fluminense"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.radio_button :sexo, 'M', :checked => true %> Masculino
    <%= f.radio_button :sexo, 'F' %> Feminino
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :salario %><br>
    <%= f.text_field :salario %>
  </div>
  <div class="field">
    <%= f.label :dtadmissao %><br>
    <%= f.text_field :dtadmissao, class: 'datepicker' %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', funcionarios_path ,  class: "btn btn-default " %>
  </div>
<script>
$(document).ready(function(){
  $('.datepicker').datepicker({format: 'dd-mm-yyyy'});
  $('#matricula').inputmask("9999.9.999.9999");  
});
</script>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form' %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Funcionários</h1>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Sexo</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Salario</th>
      <th>Data Adminissão</th>
      <th>Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.matricula %></td>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.sexo %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.salario %></td>
        <td><%= funcionario.dtadmissao %></td>
        <td><%= link_to '', edit_funcionario_path(funcionario), class: "glyphicon glyphicon-pencil" %>
        <%= link_to '', funcionario, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Funcionário', new_funcionario_path, class: "btn btn-default " %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form' %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @funcionario.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @funcionario.sexo %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.salario %>
</p>
<p>
  <strong>Data Admissão:</strong>
  <%= @funcionario.dtadmissao %>
</p>

<%= link_to 'Editar', edit_funcionario_path(@funcionario), class: "btn btn-default " %> |
<%= link_to ' Voltar', funcionarios_path ,  class: "btn btn-default " %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">Projeto</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to ' Empresa', paginas_index_path,class: "glyphicon glyphicon-home" %>
        </li>
        <li>
          <%= link_to ' Localização', paginas_localizacao_path ,class: "glyphicon glyphicon-map-marker"%></li> 
        <li>
          <%= link_to ' Funcionários', funcionarios_path ,class: "glyphicon glyphicon-user"%>
        </li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cecilia</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">	
				<%= render "layouts/navbar" %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="panel-body">
					<%= yield %>	
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
				</div>
			</div>
		</div> <!-- row -->
	</div> <!-- container -->

</body>
</html>

app/views/paginas/index.html.erb
<h1>Paginas#index</h1>
<p>Find me in app/views/paginas/index.html.erb</p>

app/views/paginas/localizacao.html.erb
<h1>Paginas#localizacao</h1>
<p>Find me in app/views/paginas/localizacao.html.erb</p>
<%= @empresa %>